import '../models/user.dart';

class DemoDataService {
  static List<UserModel> getDemoProfiles() {
    return [
      UserModel(
        id: 'ava',
        name: 'Ava',
        age: 26,
        bio: 'Amatrice de tech et de cafés, toujours prête pour une nouvelle aventure!',
        photos: ['assets/images/p1.jpg'],
        interests: ['technologie', 'voyages', 'musique', 'photographie', 'nature'],
        location: 'Paris',
        latitude: 48.8566,
        longitude: 2.3522,
        gender: 'femme',
        lookingFor: 'homme',
        job: 'Développeuse web',
        education: 'Master en informatique',
        verified: true,
        isOnline: true,
      ),
      UserModel(
        id: 'leo',
        name: 'Leo',
        age: 28,
        bio: 'Musique, randos et coding. Je cherche quelqu\'un pour partager mes passions.',
        photos: ['assets/images/p2.jpg'],
        interests: ['musique', 'sport', 'voyages', 'lecture', 'cuisine'],
        location: 'Lyon',
        latitude: 45.7640,
        longitude: 4.8357,
        gender: 'homme',
        lookingFor: 'femme',
        job: 'Chef de projet',
        education: 'École de commerce',
        verified: false,
        isOnline: false,
        lastSeen: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      UserModel(
        id: 'maya',
        name: 'Maya',
        age: 24,
        bio: 'Photographe en herbe, passionnée par l\'art et les voyages.',
        photos: ['assets/images/p3.jpg'],
        interests: ['photo', 'art', 'voyages', 'cinéma', 'danse'],
        location: 'Marseille',
        latitude: 43.2965,
        longitude: 5.3698,
        gender: 'femme',
        lookingFor: 'tous',
        job: 'Photographe freelance',
        education: 'École de photographie',
        verified: true,
        isOnline: true,
      ),
      UserModel(
        id: 'lucas',
        name: 'Lucas',
        age: 30,
        bio: 'Sportif du dimanche et entrepreneur de la semaine. Équilibre est ma devise!',
        photos: ['assets/images/p1.jpg'],
        interests: ['sport', 'entrepreneuriat', 'technologie', 'voyages', 'gastronomie'],
        location: 'Bordeaux',
        latitude: 44.8378,
        longitude: -0.5792,
        gender: 'homme',
        lookingFor: 'femme',
        job: 'Fondateur de startup',
        education: 'MBA',
        verified: true,
        isOnline: false,
        lastSeen: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      UserModel(
        id: 'chloe',
        name: 'Chloé',
        age: 27,
        bio: 'Yoga et méditation sont mes rituels quotidiens. À la recherche de la sérénité.',
        photos: ['assets/images/p2.jpg'],
        interests: ['yoga', 'méditation', 'nature', 'lecture', 'bien-être'],
        location: 'Toulouse',
        latitude: 43.6047,
        longitude: 1.4442,
        gender: 'femme',
        lookingFor: 'homme',
        job: 'Professeure de yoga',
        education: 'Formation en bien-être',
        verified: false,
        isOnline: true,
      ),
      UserModel(
        id: 'maxime',
        name: 'Maxime',
        age: 32,
        bio: 'Cinéphile invétéré et collectionneur de vinyles. La culture avant tout!',
        photos: ['assets/images/p3.jpg'],
        interests: ['cinéma', 'musique', 'lecture', 'art', 'histoire'],
        location: 'Lille',
        latitude: 50.6292,
        longitude: 3.0573,
        gender: 'homme',
        lookingFor: 'autre',
        job: 'Bibliothécaire',
        education: 'Master en histoire de l\'art',
        verified: true,
        isOnline: false,
        lastSeen: DateTime.now().subtract(const Duration(days: 1)),
      ),
      UserModel(
        id: 'emma',
        name: 'Emma',
        age: 25,
        bio: 'Passionnée de mode et de design. Je crée ma propre ligne de vêtements.',
        photos: ['assets/images/p1.jpg'],
        interests: ['mode', 'design', 'art', 'voyages', 'photographie'],
        location: 'Nice',
        latitude: 43.7102,
        longitude: 7.2620,
        gender: 'femme',
        lookingFor: 'femme',
        job: 'Styliste',
        education: 'École de mode',
        verified: false,
        isOnline: true,
      ),
      UserModel(
        id: 'nathan',
        name: 'Nathan',
        age: 29,
        bio: 'Chef cuisinier qui aime voyager pour découvrir de nouvelles saveurs.',
        photos: ['assets/images/p2.jpg'],
        interests: ['cuisine', 'voyages', 'photographie', 'vin', 'culture'],
        location: 'Strasbourg',
        latitude: 48.5846,
        longitude: 7.7507,
        gender: 'homme',
        lookingFor: 'tous',
        job: 'Chef cuisinier',
        education: 'École de cuisine',
        verified: true,
        isOnline: false,
        lastSeen: DateTime.now().subtract(const Duration(hours: 5)),
      ),
    ];
  }
}
